/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minipaint;

import java.awt.BorderLayout;
import java.awt.Color;
import java.util.*;
import java.awt.Graphics;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Reem
 */
public class Frontend extends javax.swing.JFrame implements DrawingEngine {

    /**
     * Creates new form Frontend
     */
    public Frontend() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new DrawingPanel();
        squareButton = new javax.swing.JButton();
        circleButton = new javax.swing.JButton();
        lineButton = new javax.swing.JButton();
        rectButton = new javax.swing.JButton();
        jCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        colorizeButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vector Drawing Application");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        squareButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        squareButton.setForeground(new java.awt.Color(0, 0, 204));
        squareButton.setText("Square");
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });

        circleButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        circleButton.setForeground(new java.awt.Color(0, 0, 204));
        circleButton.setText("Circle");
        circleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circleButtonActionPerformed(evt);
            }
        });

        lineButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lineButton.setForeground(new java.awt.Color(0, 0, 204));
        lineButton.setText("Line Segment");
        lineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineButtonActionPerformed(evt);
            }
        });

        rectButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rectButton.setForeground(new java.awt.Color(0, 0, 204));
        rectButton.setText("Rectangle");
        rectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectButtonActionPerformed(evt);
            }
        });

        jCombo.setEditable(true);
        jCombo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCombo.setForeground(new java.awt.Color(0, 0, 153));
        jCombo.setSelectedIndex(-1);
        jCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText(" Select Shape");

        colorizeButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        colorizeButton.setText("Colorize");
        colorizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorizeButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(circleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rectButton)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(circleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colorizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineButtonActionPerformed
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField lineField = new JTextField(5);
        //JTextField color = new JTextField(5);

        JPanel panel = new JPanel();
        panel.add(new JLabel("X:"));
        panel.add(xField);
        panel.add(new JLabel("Y:"));
        panel.add(yField);
        panel.add(new JLabel("Length:"));
        panel.add(lineField);
        //panel.add(new JLabel("Outline color:"));
        //panel.add(color);

        try {
            int result = JOptionPane.showConfirmDialog(null, panel,
                    "Enter Line Properties", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (xField.getText().isEmpty() || yField.getText().isEmpty() || lineField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter values for X, Y, and length.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (Double.parseDouble(xField.getText()) > 400
                        || Double.parseDouble(yField.getText()) > 500
                        || Double.parseDouble(lineField.getText()) > 200) {
                    JOptionPane.showMessageDialog(null, "Numbers are too big", "Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Line line = new Line();
                Point position = new Point();
                position.setLocation(Double.parseDouble(xField.getText()), Double.parseDouble(yField.getText()));
                Map<String, Double> map = new HashMap<>();
                map.put("length", Double.valueOf(lineField.getText()));
                line.setProperties(map);
                Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLACK);
                line.setColor(c);

                line.setPosition(position);
                shapes.add(line);
                jPanel1.repaint();
                jCombo.addItem("Line" + i);
                i++;

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter proper Numbers", "Message", JOptionPane.ERROR_MESSAGE);
        }    }//GEN-LAST:event_lineButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField sidelengthField = new JTextField(5);
        //JTextField color = new JTextField(5);

        JPanel panel = new JPanel();
        panel.add(new JLabel("X:"));
        panel.add(xField);
        panel.add(new JLabel("Y:"));
        panel.add(yField);
        panel.add(new JLabel("Side Length:"));
        panel.add(sidelengthField);
        //panel.add(new JLabel("Outline color:"));
        //panel.add(color);

        try {
            int result = JOptionPane.showConfirmDialog(null, panel,
                    "Enter Line Properties", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (xField.getText().isEmpty() || yField.getText().isEmpty() || sidelengthField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter values for X, Y, and length.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (Double.parseDouble(xField.getText()) > 400
                        || Double.parseDouble(yField.getText()) > 500
                        || Double.parseDouble(sidelengthField.getText()) > 200) {
                    JOptionPane.showMessageDialog(null, "Numbers are too big", "Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Square square = new Square();
                Point position = new Point();
                position.setLocation(Double.parseDouble(xField.getText()), Double.parseDouble(yField.getText()));
                Map<String, Double> map = new HashMap<>();
                map.put("length", Double.valueOf(sidelengthField.getText()));
                square.setProperties(map);
                Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLACK);
                square.setColor(c);

                square.setPosition(position);
                shapes.add(square);
                jPanel1.repaint();
                jCombo.addItem("Square" + i);
                i++;

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter proper Numbers", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_squareButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedIndex = jCombo.getSelectedIndex();
        if (selectedIndex >= 0) {
            shapes.remove(selectedIndex);
            jCombo.removeItemAt(selectedIndex);
            jPanel1.repaint();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a shape.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void circleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circleButtonActionPerformed
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField radiusField = new JTextField(5);
        //JTextField color = new JTextField(5);

        JPanel panel = new JPanel();
        panel.add(new JLabel("X:"));
        panel.add(xField);
        panel.add(new JLabel("Y:"));
        panel.add(yField);
        panel.add(new JLabel("Radius:"));
        panel.add(radiusField);
        //panel.add(new JLabel("Outline color:"));
        //panel.add(color);

        try {
            int result = JOptionPane.showConfirmDialog(null, panel,
                    "Enter Circle Properties", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (xField.getText().isEmpty() || yField.getText().isEmpty() || radiusField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter values for X, Y, and radius.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (Double.parseDouble(xField.getText()) > 400
                        || Double.parseDouble(yField.getText()) > 500
                        || Double.parseDouble(radiusField.getText()) > 200) {
                    JOptionPane.showMessageDialog(null, "Numbers are too big", "Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Circle circle = new Circle();
                Point position = new Point();
                position.setLocation(Double.parseDouble(xField.getText()), Double.parseDouble(yField.getText()));
                Map<String, Double> map = new HashMap<>();
                map.put("radius", Double.valueOf(radiusField.getText()));
                circle.setProperties(map);
                Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLACK);
                circle.setColor(c);

                circle.setPosition(position);
                shapes.add(circle);
                jPanel1.repaint();
                jCombo.addItem("Circle" + i);
                i++;

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter proper Numbers", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_circleButtonActionPerformed

    private void jComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboActionPerformed

    }//GEN-LAST:event_jComboActionPerformed

    private void rectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectButtonActionPerformed
        JTextField xField = new JTextField(5);
        JTextField yField = new JTextField(5);
        JTextField heightField = new JTextField(5);
        JTextField widthField = new JTextField(5);

        JPanel panel = new JPanel();
        panel.add(new JLabel("X:"));
        panel.add(xField);
        panel.add(new JLabel("Y:"));
        panel.add(yField);
        panel.add(new JLabel("Height:"));
        panel.add(heightField);
        panel.add(new JLabel("Width:"));
        panel.add(widthField);
        //panel.add(new JLabel("Outline color:"));
        //panel.add(color);

        try {
            int result = JOptionPane.showConfirmDialog(null, panel,
                    "Enter Circle Properties", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) {

                if (xField.getText().isEmpty() || yField.getText().isEmpty() || heightField.getText().isEmpty() || widthField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter values for X, Y, and radius.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (Double.parseDouble(xField.getText()) > 400
                        || Double.parseDouble(yField.getText()) > 500
                        || Double.parseDouble(heightField.getText()) > 200 || Double.parseDouble(widthField.getText()) > 200) {
                    JOptionPane.showMessageDialog(null, "Numbers are too big", "Message", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Rectangle rect = new Rectangle();
                Point position = new Point();
                position.setLocation(Double.parseDouble(xField.getText()), Double.parseDouble(yField.getText()));
                Map<String, Double> map = new HashMap<>();
                map.put("height", Double.valueOf(heightField.getText()));
                map.put("width", Double.valueOf(widthField.getText()));
                rect.setProperties(map);
                Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLACK);
                rect.setColor(c);

                rect.setPosition(position);
                shapes.add(rect);
                jPanel1.repaint();
                jCombo.addItem("Rectangle" + i);
                i++;

            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter proper Numbers", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_rectButtonActionPerformed

    private void colorizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorizeButtonActionPerformed
        int selectedIndex = jCombo.getSelectedIndex();
        if (selectedIndex != -1) {
            Shape selectedShape = shapes.get(selectedIndex);
            Color fillColor = JColorChooser.showDialog(null, "Choose Fill Color", Color.BLACK);
            if (fillColor != null) {
                selectedShape.setFillColor(fillColor);
                jPanel1.repaint();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a shape to colorize.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_colorizeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontend().setVisible(true);
            }
        });
    }

    public class ColorChooser {

        public static void main(String[] args) {
            JFrame frame = new JFrame("Color Chooser Example");

            frame.setSize(300, 200);

            JButton chooseColorButton = new JButton("Choose Color");
            chooseColorButton.addActionListener(e -> {
                Color selectedColor = JColorChooser.showDialog(frame, "Choose a Color", Color.BLACK);
                if (selectedColor != null) {

                    frame.getContentPane().setBackground(selectedColor);
                }
            });

            frame.add(chooseColorButton, BorderLayout.CENTER);
            frame.setVisible(true);
        }
    }

    @Override
    public void addShape(Shape shape) {
        shapes.add(shape);
        jPanel1.repaint();
    }

    @Override
    public void removeShape(Shape shape) {
        shapes.remove(shape);
        jPanel1.repaint();
    }

    @Override
    public Shape[] getShapes() {
        return shapes.toArray(new Shape[0]);
    }

    @Override
    public void refresh(Graphics canvas) {
        for (Shape shape : shapes) {
            shape.draw(canvas);
            shape.colorize(canvas);
        }
    }

    private class DrawingPanel extends JPanel {

        @Override
        protected void paintComponent(Graphics canvas) {
            super.paintComponent(canvas);
            refresh(canvas);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circleButton;
    private javax.swing.JButton colorizeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JComboBox<String> jCombo;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lineButton;
    private javax.swing.JButton rectButton;
    private javax.swing.JButton squareButton;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Shape> shapes = new ArrayList<>();
    int i = 0;
}
